### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by AnneKitsune** [Xaeroxe/atom-racer#3]
[Enter steps to reproduce:]

1. Installed everything at https://atom.io/users/Xaeroxe/stars in the order they are shown

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: [racer-plus](https://github.com/xaeroxe/atom-racer) package 2.0.0

### Stack Trace

Uncaught TypeError: Bad argument

```
At /usr/share/atom/resources/app/src/buffered-process.js:392

TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:399:9)
    at BufferedProcess.spawn (/usr/share/atom/resources/app/src/buffered-process.js:321:63)
    at BufferedProcess.start (/usr/share/atom/resources/app/src/buffered-process.js:127:20)
    at new BufferedProcess (/usr/share/atom/resources/app/src/buffered-process.js:112:18)
    at /packages/racer-plus/lib/racer-client.coffee:47:18)
    at /packages/racer-plus/lib/racer-provider.coffee:13:20)
    at Object.getRacerProvider (/packages/racer-plus/lib/racer.coffee:50:26)
    at Object.provideAutocompletion (/packages/racer-plus/lib/racer.coffee:54:6)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app/src/package.js:443:75)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:256:22)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:690:42)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -1:43.5.0 core:select-all (input.hidden-input)
     -1:41.7.0 core:backspace (input.hidden-input)
     -1:40.1.0 core:confirm (input.hidden-input)
     -1:31.3.0 core:select-all (input.hidden-input)
     -1:28.2.0 core:confirm (input.hidden-input)
     -1:20.8.0 core:select-all (input.hidden-input)
     -1:20.6.0 core:backspace (input.hidden-input)
     -1:18.4.0 core:confirm (input.hidden-input)
     -1:06.1.0 core:select-all (input.hidden-input)
     -1:05.8.0 core:backspace (input.hidden-input)
     -1:03.1.0 core:confirm (input.hidden-input)
     -0:59.1.0 core:select-all (input.hidden-input)
     -0:58.9.0 core:backspace (input.hidden-input)
     -0:52.3.0 core:select-all (input.hidden-input)
     -0:52.1.0 core:backspace (input.hidden-input)
     -0:50.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
build 0.69.0 
build-cargo 2.0.0 
busy 0.7.0 
busy-signal 1.4.3 
highlight-selected 0.13.1 
intentions 1.1.5 
language-rust 0.4.12 
linter 2.2.0 
linter-rust 0.8.0 
linter-ui-default 1.6.10 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
platformio-ide-terminal 2.7.0 
racer 0.20.0 
racer-plus 2.0.0 
```

**Comment by Xaeroxe** [comment]
>racer 0.20.0 
racer-plus 2.0.0 

This might be a problem, those packages aren't supposed to exist together.  I know it was included in the list I told you to install, but uninstall the racer package (not racer-plus) and try again.

**Comment by Xaeroxe** [comment]
@jojolepro confirmed on gitter this was resolved by my suggestion.
